apiVersion: schedule.rs/v1
kind: TDSet
metadata:
  name: tdset-hello-world
  namespace: temp
spec:
  container:
    image: crccheck/hello-world
    port: 8000
  schedulingConfig:
    - startTime: 18
      endTime: 19
      replica: 5
    - startTime: 1
      endTime: 2
      replica: 1
  defaultReplica: 3
