---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - schedule.rs
  resources:
  - tdsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schedule.rs
  resources:
  - tdsets/finalizers
  verbs:
  - update
- apiGroups:
  - schedule.rs
  resources:
  - tdsets/status
  verbs:
  - get
  - patch
  - update
